### ISSUE TITLE
Basic optimizations for performance

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#177]
Currently the page is not optimized at all on preview.thetyee.ca. Here are the main items that need to be addressed:

HIGH PRIORITY:
- [x] ~~Pre-process .less files and output them as CSS~~ [Removed the .less references]
- [x] Concatenate, minify, and cache-stamp CSS assets #182 
- [x] Concatenate, minify, and cache-stamp JavaScript assets #183 
- [x] Specify image dimensions in the Latest Stories blocks 
- [x] Fix this http://preview.thetyee.ca/design-article.thetyee.ca/ui/css/empty.gif Failed to load
- [x] ~~Move Polyfill function into a .js file~~
- [x] Remove console.log statements from article_custom.js
- [x] Remove unused .js files, like article.js, article_subscription_popup.js, backbone.js, etc. [Phillip will review and make a list to remove] #179
- [x] "/design-article.thetyee.ca/ui/img/favicon.ico"> 4xx status code, preventing rewriting of http://pagespeed.thetyee.ca/design-article.thetyee.ca/ui/img/favicon.ico 
- [ ] Re-writing `article.css` is blocked on https://github.com/TheTyee/design-article.thetyee.ca/issues/249
- [x] Optimize remaining images 
- [x] Set proper cache control headers on all static resources 
- [x] Add gzip compression to svg files (ask GT support)

PERFORMANCE QUESTIONS:
- [x] Is there a newer async version of the Disqus code? [Phillip will check] #180
- [x] Why are share_fb and share_tw in a script tag and not in a .js file?

**Comment by phillipadsmith** [comment]
Getting pretty darn fast for a new site:
https://gtmetrix.com/reports/pagespeed.thetyee.ca/mW2NdfcE (Chrome, desktop)
https://gtmetrix.com/reports/pagespeed.thetyee.ca/ZlnWewmQ (FF, desktop)
https://gtmetrix.com/reports/pagespeed.thetyee.ca/LyJoH3jj (Chrome Android, mobile)

**Comment by phillipadsmith** [comment]
Okay, I'm going to call this closed.

The article.css isn't being minimized because of the parsing errors, but we can live with that. 

Also getting some decent improvements on non-article pages too:
https://gtmetrix.com/compare/3MVDERCh/IFvbAzdJ
